[package]
name = "dimage-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = {version = "1", features = ["derive"]}
serde_json = "1"
toml = "0.8.22"
clap = {version = "4", features = ["derive"]}
